name: ml4litho
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.6.1
  - astor=0.7.1
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15
  - cloudpickle=0.6.1
  - cycler=0.10.0
  - dask-core=0.20.0
  - decorator=4.3.0
  - freetype=2.9.1
  - gast=0.2.0
  - grpcio=1.12.1
  - h5py=2.8.0
  - hdf5=1.10.2
  - imageio=2.4.1
  - intel-openmp=2019.0=118
  - jpeg=9b
  - keras-applications=1.0.6
  - keras-preprocessing=1.0.5
  - kiwisolver=1.0.1
  - libcxx=4.0
  - libedit=3.1
  - libffi=3.2.1
  - libgfortran=3.0
  - libpng=1.6.35
  - libprotobuf=3.6.1
  - libtiff=4.0.9
  - markdown=3.0.1
  - matplotlib=2
  - mkl=2019.0=118
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - networkx=2.2
  - numpy=1.15.3
  - numpy-base=1.15.3
  - olefile=0.46
  - openssl=1.1.1
  - pillow=5.3.0
  - pip
  - protobuf=3.6.1
  - pyparsing=2.3.0
  - pyqt[version='<5']
  - python=2.7
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pywavelets=1.0.1
  - readline=7.0
  - scikit-image=0.14.0
  - scipy=1.1.0
  - setuptools=40.5.0
  - six
  - sqlite=3.25.2
  - tensorboard=1.11.0
  - tensorflow=1.11.0
  - tensorflow-base=1.11.0
  - termcolor=1.1.0
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1.1
  - werkzeug=0.14.1
  - wheel=0.32.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - dask==0.20.0
